Repository saritasa-nest/saritasa-devops-helm-charts, pull requests merged in 2022-02, with the labels that each got.

#10 feat: add rbac for client devs/team (similar to saritasa developers role/groups)
  charts/jitsi-helm/README.md
  charts/jitsi-helm/charts/prosody/README.md
  charts/rbac/Chart.yaml
  charts/rbac/README.md
  charts/rbac/templates/client/apps.yaml
  charts/rbac/templates/client/ci.yaml
  charts/rbac/templates/client/cluster.yaml
  charts/rbac/templates/client/ingress-nginx.yaml
  charts/rbac/templates/client/mssql.yaml
  charts/rbac/templates/client/mysql.yaml
  charts/rbac/templates/client/postgres.yaml
  charts/rbac/values.yaml
Labels: enhancement, Needs Review

#11 feat: halt buildpack-frontend run if 'npm run build:<env>' failed
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/values.yaml
Labels: Needs Review

#13 feat: fixed git push loop in tekton kustomize task
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/templates/common/tasks/kustomize.yaml
Labels: bug, Needs Review
