Repository saritasa-nest/saritasa-devops-helm-charts, pull requests merged in 2022-07, with the labels that each got.

#32 feat: add node:16 dynamic detection from package.json. if not defined node:14 is used
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/templates/buildpacks/pipelines/_buildpack.yaml
  charts/tekton-pipelines/templates/buildpacks/tasks/_buildpack.yaml
  charts/tekton-pipelines/templates/common/tasks/detect-nodejs-version.yaml
  charts/tekton-pipelines/values.yaml
Labels: enhancement, Needs Review

#34 feat: add nodeSelector/affinity to tekton-triggers-controller
  charts/tekton/Chart.yaml
  charts/tekton/README.md
  charts/tekton/templates/tekton-triggers.yaml
Labels: enhancement, Needs Review

#33 feat: add eventlistener node selector
  charts/tekton-apps/Chart.yaml
  charts/tekton-apps/README.md
  charts/tekton-apps/templates/eventlistener.yaml
  charts/tekton-apps/values.yaml
Labels: enhancement, Needs Review

#35 feature/improve argocd deploy task
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/templates/common/tasks/argocd-deploy.yaml
  charts/tekton-pipelines/values.yaml
Labels: enhancement, Needs Review

#36 feat: fixed access to batch api for developers
  charts/rbac/Chart.yaml
  charts/rbac/README.md
  charts/rbac/templates/developers/apps.yaml
Labels: bug, Needs Review

#37 feature/upgrade rbac to 0.1.8
  .github/workflows/release.yml
  charts/demo/README.md
  charts/jitsi-helm/README.md
  charts/jitsi-helm/charts/prosody/README.md
  charts/opsgenie-heartbeat/README.md
  charts/rbac/Chart.yaml
  charts/rbac/README.md
  charts/tekton-apps/README.md
  charts/tekton-pipelines/README.md
  charts/tekton/README.md
Labels: enhancement
