Repository saritasa-nest/saritasa-devops-helm-charts, pull requests merged in 2022-03, with the labels that each got.

#16 Fix buildpack-frontend task failing
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/values.yaml
Labels: Needs Review

#19 feature/add npm to dotnet pipeline
  charts/jitsi-helm/README.md
  charts/rbac/README.md
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/values.yaml
Labels: enhancement, Needs Review

#20 feature/upgrade jitsi
  charts/jitsi-helm/Chart.yaml
  charts/jitsi-helm/README.md
  charts/jitsi-helm/charts/prosody/Chart.yaml
  charts/jitsi-helm/charts/prosody/README.md
  charts/jitsi-helm/charts/prosody/templates/statefulset.yaml
  charts/jitsi-helm/docs/index.yaml
  charts/jitsi-helm/docs/jitsi-meet-0.2.1.tgz
  charts/jitsi-helm/docs/jitsi-meet-1.0.0.tgz
  charts/jitsi-helm/docs/jitsi-meet-1.1.0.tgz
  charts/jitsi-helm/docs/jitsi-meet-1.2.0.tgz
  charts/jitsi-helm/docs/jitsi-meet-1.2.1.tgz
  charts/jitsi-helm/docs/jitsi-meet-1.2.2.tgz
  charts/jitsi-helm/templates/common-configmap.yaml
  charts/jitsi-helm/templates/ingress.yaml
  charts/jitsi-helm/templates/jibri/_helper.tpl
  charts/jitsi-helm/templates/jibri/configmap.yaml
  charts/jitsi-helm/templates/jibri/deployment.yaml
  charts/jitsi-helm/templates/jibri/persistentvolumeclaim.yaml
  charts/jitsi-helm/templates/jibri/service.yaml
  charts/jitsi-helm/templates/jibri/xmpp-secret.yaml
  charts/jitsi-helm/templates/jicofo/configmap.yaml
  charts/jitsi-helm/templates/jicofo/deployment.yaml
  charts/jitsi-helm/templates/jicofo/xmpp-secret.yaml
  charts/jitsi-helm/templates/jvb/configmap.yaml
  charts/jitsi-helm/templates/jvb/deployment.yaml
  charts/jitsi-helm/templates/jvb/metrics-prometheus.yaml
  charts/jitsi-helm/templates/jvb/metrics-service.yaml
  charts/jitsi-helm/templates/jvb/service.yaml
  charts/jitsi-helm/templates/jvb/xmpp-secret.yaml
  charts/jitsi-helm/templates/web/configmap.yaml
  charts/jitsi-helm/templates/web/deployment.yaml
  charts/jitsi-helm/values.yaml
Labels: enhancement
