Repository saritasa-nest/saritasa-devops-helm-charts, pull requests merged in 2023-08, with the labels that each got.

#82 feat: use 1.5.4 docker image for `terraform-pod`
  charts/terraform-pod/Chart.yaml
  charts/terraform-pod/README.md
  charts/terraform-pod/values.yaml
Labels: enhancement, Needs Review

#79 feat: poetry for django pipeline step
  charts/tekton-apps/Chart.yaml
  charts/tekton-apps/README.md
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/values.yaml
Labels: enhancement, Needs Review, chart/tekton-pipelines

#84 fix: disable hashes for poetry export
  charts/tekton-pipelines/Chart.yaml
  charts/tekton-pipelines/README.md
  charts/tekton-pipelines/values.yaml
Labels: bug, Needs Review, chart/tekton-pipelines

#83 feat: less frequent healthchecks for WordPress
  charts/tekton-apps/Chart.yaml
  charts/tekton-apps/README.md
  charts/tekton-apps/templates/wordpress/argocd_applications.yaml
Labels: Needs Review

#85 feat: release terraform 1.5.6
  charts/terraform-pod/Chart.yaml
  charts/terraform-pod/README.md
  charts/terraform-pod/values.yaml
Labels: enhancement, Needs Review
