Repository saritasa-nest/saritasa-devops-helm-charts, pull requests merged in 2024-09, with the labels that each got.

#130 feat: add kubernetes event exporter dashboard
  CHANGELOG.md
  charts/grafana-dashboards/Chart.yaml
  charts/grafana-dashboards/README.md
  charts/grafana-dashboards/templates/kubernetes/event-exporter.yaml
  charts/grafana-dashboards/values.yaml
Labels: Needs Review, chart/grafana-dashboards

#131 feat: edit updateStrategy
  CHANGELOG.md
  charts/tekton-apps/Chart.yaml
  charts/tekton-apps/templates/wordpress/argocd_applications.yaml
Labels: enhancement, Needs Review

#133 fix: edit home dashboard
  CHANGELOG.md
  charts/grafana-dashboards/Chart.yaml
  charts/grafana-dashboards/README.md
  charts/grafana-dashboards/templates/default/home.yaml
Labels: enhancement, Needs Review, chart/grafana-dashboards

#134 fix: RBAC roles had invalid definition
  CHANGELOG.md
  charts/rbac/Chart.yaml
  charts/rbac/README.md
  charts/rbac/templates/client/apps.yaml
  charts/rbac/templates/developers/apps.yaml
Labels: bug, Needs Review

#132 feat: update path for readinessProbe and customLivenessProbe
  CHANGELOG.md
  charts/tekton-apps/Chart.yaml
  charts/tekton-apps/templates/wordpress/argocd_applications.yaml
Labels: enhancement, Needs Review
